# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-18 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0002_auto_20141227_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('keyword', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_image', to='generic.Keyword')),
            ],
        ),
    ]
